CREATE TABLE IF NOT EXISTS campaign_link_analyses (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL,
    url VARCHAR(1000) NOT NULL,
    campaign_name VARCHAR(255),
    campaign_id VARCHAR(255),
    status VARCHAR(50),
    objective VARCHAR(255),
    content_type VARCHAR(50),
    start_date DATE,
    end_date DATE,
    budget DOUBLE PRECISION,
    budget_type VARCHAR(50),
    total_spend DOUBLE PRECISION,
    reach BIGINT,
    impressions BIGINT,
    clicks BIGINT,
    ctr DOUBLE PRECISION,
    likes INT,
    comments INT,
    shares INT,
    saves INT,
    video_views BIGINT,
    engagement_rate DOUBLE PRECISION,
    conversions INT,
    cost_per_result DOUBLE PRECISION,
    cpc DOUBLE PRECISION,
    cpm DOUBLE PRECISION,
    roas DOUBLE PRECISION,
    cta_type VARCHAR(100),
    author_handle VARCHAR(255),
    caption_snippet VARCHAR(2000),
    thumbnail_url VARCHAR(1000),
    is_authorized_connected_account BOOLEAN NOT NULL DEFAULT FALSE,
    authorization_status VARCHAR(100),
    audience_json TEXT,
    creative_details_json TEXT,
    daily_metrics_json TEXT,
    recommendations_json TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_campaign_link_analyses_user_id ON campaign_link_analyses(user_id);
CREATE INDEX IF NOT EXISTS idx_campaign_link_analyses_created_at ON campaign_link_analyses(created_at DESC);
